version: "3.9"

x-project-volume:
  &services-volume
  type: bind
  source: ./
  target: /var/www

services:
  mysql:
    image: mariadb:10.1.38
    ports:
      - "3306:3306"
    volumes:
      - mysql-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

  apache:
    build: ./apache
    ports:
      - "80:80"
      - "443:443"
    links:
      - mysql
    volumes:
      - *services-volume
#    logging:
#      driver: none
#    entrypoint:
#      - /bin/sh
#      - -c
#      - sleep 86400

#test-apache-1  | AH00526: Syntax error on line 144 of /usr/local/apache2/conf/extra/httpd-ssl.conf:
#test-apache-1  | SSLCertificateFile: file '/usr/local/apache2/conf/server.crt' does not exist or is empty
#  test-apache-1 exited with code 1


  php:
    container_name: php
    build:
      args:
        - PROJECT_DIR=.
    links:
      - mysql
    volumes:
      - ./app:/var/www/app:delegated
      - php-volume:/var/www/vendor
#    environment:
#      PHP_IDE_CONFIG: ${DOCKER_PHP_IDE_CONFIG}
#      XDEBUG_SESSION: ${DOCKER_XDEBUG_SESSION}
#      XDEBUG_CLIENT_HOST: ${DOCKER_XDEBUG_CLIENT_HOST}
    logging:
      driver: "json-file"
      options:
        max-size: "20k" # max size of each log file
        max-file: "1" # maximum number of log files

volumes:
  mysql-volume:
  php-volume:
